# Generated by Django 3.0 on 2021-03-23 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('login_date', models.DateTimeField(auto_now=True, verbose_name='登入時間')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member', verbose_name='登入帳號UID')),
            ],
        ),
    ]
