# Generated by Django 3.0 on 2021-04-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_auto_20210419_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(blank=True, choices=[('1', '在線'), ('2', '忙線'), ('3', '離線')], default='3', max_length=1, null=True, verbose_name='狀態'),
        ),
    ]
