# Generated by Django 3.0 on 2021-05-05 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_auto_20210420_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='pet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='寵物id')),
                ('pet_name', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='寵物名稱')),
                ('chip', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='晶片號碼')),
                ('category', models.PositiveIntegerField(choices=[(1, '貓'), (2, '狗')], null=True, verbose_name='動物別')),
                ('breed', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='品種')),
                ('sex', models.PositiveIntegerField(choices=[(1, '雄'), (2, '雌')], null=True, verbose_name='性別')),
                ('age', models.CharField(blank=True, default='', max_length=8, null=True, verbose_name='年齡')),
                ('weight', models.CharField(blank=True, default='', max_length=8, null=True, verbose_name='體重')),
                ('description', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='介紹')),
                ('photo', models.CharField(blank=True, default='', max_length=254, null=True, verbose_name='照片')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('last_modify_date', models.DateTimeField(blank=True, null=True, verbose_name='最後異動時間')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member', verbose_name='會員ID')),
            ],
        ),
    ]
