# Generated by Django 3.0 on 2021-05-10 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_pet'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='醫生id')),
                ('doc_name', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='醫生姓名')),
                ('clinic', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='診所')),
                ('title', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='職稱')),
                ('skill', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='專長')),
                ('experience', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='學經歷')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('last_modify_date', models.DateTimeField(blank=True, null=True, verbose_name='最後異動時間')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member', verbose_name='會員ID')),
            ],
        ),
    ]
