# Generated by Django 3.0 on 2021-05-10 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='是否已確認'),
        ),
    ]
