# Generated by Django 3.0 on 2021-05-23 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_doctor_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='docAppoint',
            fields=[
                ('appoint_id', models.AutoField(primary_key=True, serialize=False, verbose_name='看診表id')),
                ('set_date', models.DateField(verbose_name='設定日期')),
                ('set_hour', models.PositiveIntegerField(verbose_name='時間')),
                ('set_section', models.PositiveIntegerField(choices=[(1, '0-20分'), (2, '20-40分'), (3, '40-60分')], default=1, verbose_name='時段')),
                ('status', models.PositiveIntegerField(choices=[(1, '可預約'), (2, '不可預約'), (3, '已預約'), (4, '待確認')], default=1, verbose_name='時段')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('last_modify_date', models.DateTimeField(blank=True, null=True, verbose_name='最後異動時間')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.doctor', verbose_name='醫生ID')),
            ],
        ),
        migrations.CreateModel(
            name='userAppoint',
            fields=[
                ('user_appoint_id', models.AutoField(primary_key=True, serialize=False, verbose_name='會員預約看診id')),
                ('mark', models.PositiveIntegerField(choices=[(0, '非即時'), (0, '即時')], default=0, verbose_name='看診狀態')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('last_modify_date', models.DateTimeField(blank=True, null=True, verbose_name='最後異動時間')),
                ('appoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.docAppoint', verbose_name='看診表id')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member', verbose_name='會員ID')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.pet', verbose_name='寵物ID')),
            ],
        ),
    ]
