# Generated by Django 3.0 on 2021-05-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_docappoint_userappoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='userappoint',
            name='paid_no',
            field=models.PositiveIntegerField(default=0, verbose_name='繳費單號'),
        ),
    ]
