# Generated by Django 3.0 on 2021-05-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_userappoint_paid_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docappoint',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, '可預約'), (2, '不可預約'), (3, '已預約'), (4, '待確認')], default=1, verbose_name='狀態'),
        ),
    ]
