# Generated by Django 3.0 on 2021-05-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0012_auto_20210524_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docappoint',
            name='set_hour',
            field=models.PositiveIntegerField(verbose_name='預約時間'),
        ),
        migrations.AlterField(
            model_name='docappoint',
            name='set_section',
            field=models.PositiveIntegerField(choices=[(1, '0-20分'), (2, '20-40分'), (3, '40-60分')], default=1, verbose_name='預約時段'),
        ),
        migrations.AlterField(
            model_name='docappoint',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, '可預約'), (2, '不可預約'), (3, '已預約'), (4, '待確認')], default=1, verbose_name='預約狀態'),
        ),
        migrations.AlterField(
            model_name='userappoint',
            name='mark',
            field=models.PositiveIntegerField(choices=[(0, '非即時'), (1, '即時')], default=0, verbose_name='預約註記'),
        ),
    ]
