# Generated by Django 3.0 on 2021-05-28 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0013_auto_20210526_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docappoint',
            name='appoint_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='看診表ID'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='醫生ID'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='寵物ID'),
        ),
        migrations.AlterField(
            model_name='userappoint',
            name='appoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.docAppoint', verbose_name='看診表ID'),
        ),
        migrations.AlterField(
            model_name='userappoint',
            name='user_appoint_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='會員預約看診ID'),
        ),
        migrations.CreateModel(
            name='docComment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False, verbose_name='評價表ID')),
                ('stars', models.PositiveIntegerField(choices=[(1, '一顆星'), (2, '二顆星'), (3, '三顆星'), (4, '四顆星'), (5, '五顆星')], default=5, verbose_name='評價星數')),
                ('memo', models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='留言')),
                ('user_photo', models.CharField(blank=True, default='', max_length=254, null=True, verbose_name='照片')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('last_modify_date', models.DateTimeField(blank=True, null=True, verbose_name='最後異動時間')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.doctor', verbose_name='醫生ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member', verbose_name='會員ID')),
            ],
        ),
        migrations.CreateModel(
            name='docBH',
            fields=[
                ('bh_id', models.AutoField(primary_key=True, serialize=False, verbose_name='醫生營業時段ID')),
                ('bh1_name', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='看診時段一(起、迄)')),
                ('bh2_name', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='看診時段二(起、迄)')),
                ('bh3_name', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='看診時段三(起、迄)')),
                ('bh1_setting', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='看診時段一星期設定')),
                ('bh2_setting', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='看診時段二星期設定')),
                ('bh3_setting', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='看診時段三星期設定')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('last_modify_date', models.DateTimeField(blank=True, null=True, verbose_name='最後異動時間')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.doctor', verbose_name='醫生ID')),
            ],
        ),
        migrations.CreateModel(
            name='advisory',
            fields=[
                ('advisory_id', models.AutoField(primary_key=True, serialize=False, verbose_name='諮詢表ID')),
                ('advisory_date', models.DateField(verbose_name='諮詢日期')),
                ('advisory_time', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='時間')),
                ('fee', models.PositiveIntegerField(default=0, verbose_name='費用')),
                ('description', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='飼主描述')),
                ('case_history', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='病例史')),
                ('sympton', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='徵狀描述')),
                ('suggest', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='諮詢建議')),
                ('medcine', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='用藥')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('last_modify_date', models.DateTimeField(blank=True, null=True, verbose_name='最後異動時間')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.doctor', verbose_name='醫生ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member', verbose_name='會員ID')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.pet', verbose_name='寵物ID')),
                ('user_appoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.userAppoint', verbose_name='預約看診ID')),
            ],
        ),
    ]
