# Generated by Django 3.0 on 2021-06-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0014_auto_20210528_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='area',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='地區'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='clinic_addr',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='診所地址'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='doc_photo',
            field=models.CharField(blank=True, default='', max_length=254, null=True, verbose_name='醫生圖案'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='room_url',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='醫生會議室連結'),
        ),
    ]
