# Generated by Django 3.0 on 2021-06-12 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0015_auto_20210608_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='clinic',
            fields=[
                ('clinic_id', models.AutoField(primary_key=True, serialize=False, verbose_name='診所ID')),
                ('clinic_name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='診所名稱')),
                ('area', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='地區')),
                ('address', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='診所地址')),
                ('tel', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='電話')),
                ('serv_content', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='服務內容')),
                ('desc', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='簡介')),
                ('email', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='信箱')),
                ('photo', models.CharField(blank=True, default='', max_length=254, null=True, verbose_name='照片')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('last_modify_date', models.DateTimeField(blank=True, null=True, verbose_name='最後異動時間')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member', verbose_name='會員ID')),
            ],
        ),
        migrations.CreateModel(
            name='store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False, verbose_name='店家ID')),
                ('store_name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='店家名稱')),
                ('area', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='地區')),
                ('address', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='店家地址')),
                ('tel', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='電話')),
                ('serv_content', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='服務內容')),
                ('desc', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='簡介')),
                ('email', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='信箱')),
                ('photo', models.CharField(blank=True, default='', max_length=254, null=True, verbose_name='照片')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('last_modify_date', models.DateTimeField(blank=True, null=True, verbose_name='最後異動時間')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member', verbose_name='會員ID')),
            ],
        ),
        migrations.CreateModel(
            name='storeBH',
            fields=[
                ('bh_id', models.AutoField(primary_key=True, serialize=False, verbose_name='店家營業時段ID')),
                ('bh1_name', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='看診時段一(起、迄)')),
                ('bh2_name', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='看診時段二(起、迄)')),
                ('bh3_name', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='看診時段三(起、迄)')),
                ('bh1_setting', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='看診時段一星期設定')),
                ('bh2_setting', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='看診時段二星期設定')),
                ('bh3_setting', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='看診時段三星期設定')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('last_modify_date', models.DateTimeField(blank=True, null=True, verbose_name='最後異動時間')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.store', verbose_name='店家ID')),
            ],
        ),
        migrations.CreateModel(
            name='clinicBH',
            fields=[
                ('bh_id', models.AutoField(primary_key=True, serialize=False, verbose_name='診所營業時段ID')),
                ('bh1_name', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='看診時段一(起、迄)')),
                ('bh2_name', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='看診時段二(起、迄)')),
                ('bh3_name', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='看診時段三(起、迄)')),
                ('bh1_setting', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='看診時段一星期設定')),
                ('bh2_setting', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='看診時段二星期設定')),
                ('bh3_setting', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='看診時段三星期設定')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('last_modify_date', models.DateTimeField(blank=True, null=True, verbose_name='最後異動時間')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.clinic', verbose_name='診所ID')),
            ],
        ),
    ]
