# Generated by Django 3.0 on 2021-06-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0016_clinic_clinicbh_store_storebh'),
    ]

    operations = [
        migrations.AddField(
            model_name='doccomment',
            name='advisory',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='諮詢表ID'),
        ),
    ]
