# Generated by Django 3.0 on 2021-06-14 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0017_doccomment_advisory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doccomment',
            old_name='advisory',
            new_name='advisory_id',
        ),
    ]
