# Generated by Django 3.0 on 2021-06-16 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0019_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='BKLoginInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('login_success', models.BooleanField(default=False, verbose_name='登入成功/失敗')),
                ('message', models.CharField(max_length=200, verbose_name='訊息')),
                ('login_date', models.DateTimeField(auto_now=True, verbose_name='登入時間')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Account', verbose_name='登入帳號ID')),
            ],
        ),
    ]
