# Generated by Django 3.0 on 2021-06-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0020_bklogininfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='approve_account',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='確認者帳號'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='approve_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='確認時間'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='是否已確認'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='approve_account',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='確認者帳號'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='approve_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='確認時間'),
        ),
        migrations.AddField(
            model_name='store',
            name='approve_account',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='確認者帳號'),
        ),
        migrations.AddField(
            model_name='store',
            name='approve_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='確認時間'),
        ),
        migrations.AddField(
            model_name='store',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='是否已確認'),
        ),
    ]
