# Generated by Django 3.0 on 2021-07-09 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0023_socialaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberLikePost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='likeId')),
                ('isLike', models.PositiveIntegerField(choices=[(0, 'None'), (1, 'like'), (2, 'dislike')], default=0, verbose_name='是否喜歡')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('last_modify_date', models.DateTimeField(blank=True, null=True, verbose_name='最後異動時間')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member', verbose_name='會員ID')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.dynaPost', verbose_name='貼文ID')),
            ],
        ),
    ]
