# Generated by Django 3.0 on 2021-07-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0024_memberlikepost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logininfo',
            name='account',
        ),
        migrations.AddField(
            model_name='logininfo',
            name='member_id',
            field=models.IntegerField(default=0, verbose_name='會員ID'),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='member_id',
            field=models.IntegerField(default=0, verbose_name='會員ID'),
        ),
    ]
