# Generated by Django 3.0 on 2021-08-19 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0026_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='mytest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='google', max_length=200)),
                ('unique_id', models.CharField(max_length=200)),
                ('member_id', models.IntegerField(default=0, verbose_name='會員ID')),
            ],
        ),
    ]
